### PR TITLE
Delete providers/g/googlecloudplatform directory

### PR DESCRIPTION
**Pull request by Pospelove**
cloud is cursed

### CODE REVIEW

**Comment by gecube** [comment]
I hope it was a joke

**Comment by intari** [comment]
> I hope it was a joke

Why?
Are you 100% SURE it doesn't used for ANY military purpose by ANYONE?

**Comment by Pospelove** [comment]
fyi the pr is not associated with any further trolling

**Comment by cam72cam** [comment]
Locking this discussion as it is not productive.

**Pull request closed without merging**
