### PR TITLE
Update provider key adyxax/

### PR DESCRIPTION
**Pull request by adyxax**
Hi,

I made a mistake when submitting the gpg public key with which I sign my provider in #187, I pasted the gpg key I use to sign my emails instead. This PR fixes this by setting the correct public key.

I made sure to keep the same file format the automation generated the first time which uses CR LF as line endings.

Sorry for the inconvenience and thank you for your work on opentofu,

### CODE REVIEW

**Comment by adyxax** [comment]
I just force pushed an update because I forgot to sign-off my commit.

**Comment by ghost** [comment]
Hey @adyxax thank you for this PR. However, we have automation in place, could you please [re-submit the GPG form](https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+)?

**Comment by adyxax** [comment]
Yes I can, thank you for your message! I did not expect it to work since it is named "new provider key" but I will do that.

**Comment by adyxax** [comment]
The diff generated by the automation in #198 is indeed the same, so it works event for updating a key. I am closing this PR then.

**Pull request closed without merging**
