### PR TITLE
Move back some providers

### PR DESCRIPTION
**Pull request by AlekseiKulberg**

### CODE REVIEW

**Comment by RFOTQ** [comment]
My hero!

**Comment by Dok-dev** [comment]
I support it. Deleting a provider that thousands of people use is disgusting.

**Comment by cam72cam** [comment]
OpenTofu registry is a hosted project, so we must comply with applicable sanctions and laws.

**Comment by RFOTQ** [comment]
> OpenTofu registry is a hosted project, so we must comply with applicable sanctions and laws.

Any links to specific sanctions and laws that obligate you to do so?

**Comment by sys-av** [comment]
Could you give more details? Where hosted project? Which service or hoster requested to remove support of some particular cloud providers? In my understandind this open sours  project didn't provide any goods or services for cloud providers or for any other companies.

**Comment by dentist128** [comment]
> OpenTofu registry is a hosted project, so we must comply with applicable sanctions and laws.

the project cannot be called open

**Comment by abakanovskii** [comment]
more like half-way-OpenTofu :face_exhaling: 
some people are more equal than others i guess

> > OpenTofu registry is a hosted project, so we must comply with applicable sanctions and laws.
> 
> the project cannot be called open

**Comment by gecube** [comment]
Totally agree, looks like project is not free and breaks all international collaboration, particularly that Yandex is not also Russian company and has presence in other countries

so it’s ok for GitHub (which is Ms project and obliged to follow USA export restrictions) host repos for sbercloud (even I don’t like it and don’t support) and Yandex, but for open tofu it is not ok…. Strange, really?

**Comment by efadeev** [comment]
What a shame, OpenTofu. So maybe you need to change your license to BSL? Oh, wai--

**Comment by MaxOinRU** [comment]
Maybe we need to ask the Linux Foundation to look into the situation?
First was GeoIP block ONLY for Russia, i guess, and then deleting providers (not every Russian provider, just "some").

**Comment by cam72cam** [comment]
https://github.com/opentofu/opentofu/blob/main/README.md#registry-access
https://github.com/opentofu/opentofu/blob/main/TSC_SUMMARY.md#sanctions-russia-vs-registry-access

**Comment by efadeev** [comment]
> In an effort to comply with applicable sanctions, we block access from specific countries of origin.

What sanctions may affect opensource project?

**Comment by kemko** [comment]
@cam72cam Excellent answer, but not substantive. It's good that you voted to block access and said "it's because of sanctions," but where is the work shown to determine what exactly is currently prohibited by sanctions, how it specifically relates to opentofu's activities, and so on? The Miro case is illustrative, where they first announced a suspension of access, but then added that they studied the provisions in more detail and realized they could keep access open for free accounts.

**Comment by gecube** [comment]
@cam72cam there is difference between 
- ban number of providers (which are still available on github - look on my previous post, so MS is ok with it)
- restrict access by GeoIP (fair enough, ok, but then you need to ban N.Korea, Iran, Syria etc. to have a consistent position).

**Comment by DanyaSh** [comment]
`+`
"Open" Tofu

**Comment by DanyaSh** [comment]
The moment when Terraform turned out to be much more open than OpenTofu.

**Comment by ansromanov** [comment]
A good sign to return back to Terraform.

**Comment by odinsy** [comment]
nothing common with "open"

**Comment by ZaneHero** [comment]
Back to Terraform.

**Comment by kemko** [comment]
@cam72cam have you any news after consulting with lawyers?

**Comment by nnovikov** [comment]
PeonTofu now.

**Comment by gecube** [comment]
going to discuss in #824

**Comment by timurgen** [comment]
> https://github.com/opentofu/opentofu/blob/main/README.md#registry-access https://github.com/opentofu/opentofu/blob/main/TSC_SUMMARY.md#sanctions-russia-vs-registry-access

access to registry not equal to removing providers

**Comment by cam72cam** [comment]
Hi, OpenTofu Tech Lead here speaking on behalf of the Technical Steering Committee.

We have taken proactive steps to ensure compliance with relevant sanctions. We have heard the community’s feedback on this issue and are working on a more detailed response and next steps. We will update the community soon.

**Comment by fedya** [comment]
Every bomb on your heads is justified, morons.

**Comment by mi4i0** [comment]
Good decision! Totally support it! Happy that it finally happen. I hope AWS and other services will block ru region account in soonest future

**Comment by ikaygorodov** [comment]
> Hi, OpenTofu Tech Lead here speaking on behalf of the Technical Steering Committee.
> 
> We have taken proactive steps to ensure compliance with relevant sanctions. We have heard the community’s feedback on this issue and are working on a more detailed response and next steps. We will update the community soon.

And still no a word about situation.
Shame on you.
In normal projects and companies employees should have been fired immediately for this kind of sabotage.

**Comment by mi4i0** [comment]
> > Hi, OpenTofu Tech Lead here speaking on behalf of the Technical Steering Committee.
> > 
> > We have taken proactive steps to ensure compliance with relevant sanctions. We have heard the community’s feedback on this issue and are working on a more detailed response and next steps. We will update the community soon.
> 
> And still no a word about situation.
> Shame on you.
> In normal projects and companies employees should have been fired immediately for this kind of sabotage.

All done is correct. Don't pay attention to those hatters....

**Comment by eshutov** [comment]
> And still no a word about situation.

They already gave us detailed response. See #824  thread.
They don't have resources to figure out with sanctions, but they do have resources to join to the sanctions. And they don't find a logical issue here.
With such thinking is possible to justify anything. For e.g., how about a court who doesn't have a time (resources) to figure out the case and who decided to execute defendant for society safety (ofc)? That is the world they want to live in.
Don't bother them in enjoying their self-destruction.

**Comment by ikaygorodov** [comment]
> > And still no a word about situation.
> 
> They already gave us detailed response. See #824 thread. They don't have resources to figure out with sanctions, but they do have resources to join to the sanctions. And they don't find a logical issue here. With such thinking is possible to justify anything. For e.g., how about a court who doesn't have a time (resources) to figure out the case and who decided to execute defendant for society safety (ofc)? That is the world they want to live in. Don't bother them in enjoying their self-destruction.

Unfortunately you are right. We can save this day as the day, when great opensource project started to heading to its end...
With those unjustified decisions that simply does not make any sense...

**Comment by openuuuser** [comment]
Hi, 
when providers will be reverted?

**Comment by timurgen** [comment]
> Hi, when providers will be reverted?

Of course they won't, they believe everybody will forget it.

**Comment by ikaygorodov** [comment]
It doesn't make sense to wait for an adequate decisions from inadequate people.
It is obvious they will not do anything with this issue. Terraform now looks as much more open project in comparison to OpenTofu.

**Comment by odinsy** [comment]
govnoedyblyat'

**Pull request closed without merging**
