### PR TITLE
Registry | Provider - port-labs | remove unavailable version 10.1.1

### PR DESCRIPTION
**Pull request by MPTG94**
Hi,

I work for [Port](https://getport.io), we publish the port-labs Terraform provider, we had a case where we published a release with the wrong version number 10.1.1, I can see that that release appears in the OpenTofu registry.

I opened this PR to remove that release, so that users of OpenTofu can successfully pull the correct provider version (the latest version as of opening this PR is 1.10.6)

The 10.1.1 version was already deleted both from the TF registry, and also from our repository which generates and publishes the provider, so I hope after merging this updated manifest, searches for the provider in the OpenTofu registry will work as expected and will also not break in the future with new releases.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @MPTG94 I currently cannot verify that you are a member of the port-labs organization on GitHub. Please make your membership in this organization public.

Additionally, I'd like to note that we would like to treat releases as immutable since supply chain attacks are hard to mitigate otherwise, but I can see that this was a genuine mistake, so we will merge this PR once your membership has been verified.

**Comment by MPTG94** [comment]
Hey @janosdebugs, I updated the visibility status, can you check now?

**Review by ghost — APPROVED** [review]
Identity verified, however, the PR has a conflict.

**Comment by ghost** [comment]
@Yantrio could you please take a look at this?

**Review by Yantrio — APPROVED** [review]

**Comment by Yantrio** [comment]
This looks good to me. I'm happy to merge this and the version should be removed shortly :D thanks for submitting a PR for this.

**Pull request merged**
